Repository Team-Piglin/swapswap, pull requests merged in 2024-01, with the labels that each got.

#25 Design: 엔티티 설계 및 구현
  build.gradle
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/common/BaseTime.java
  src/main/java/piglin/swapswap/domain/coupon/constant/CouponType.java
  src/main/java/piglin/swapswap/domain/coupon/entity/Coupon.java
  src/main/java/piglin/swapswap/domain/deal/constant/DealStatus.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/favorite/entity/Favorite.java
  src/main/java/piglin/swapswap/domain/member/constant/UserRoleEnum.java
  src/main/java/piglin/swapswap/domain/member/entity/Member.java
  src/main/java/piglin/swapswap/domain/post/constant/Category.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/wallet/entity/Wallet.java
  src/main/java/piglin/swapswap/domain/wallethistory/entity/WalletHistory.java
  src/main/java/piglin/swapswap/global/config/JpaConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#26 Feature: 컨트롤러에서 발생하는 전역 예외 처리 구현
  src/main/java/piglin/swapswap/global/exception/comment/CommentNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/common/AuthorizationException.java
  src/main/java/piglin/swapswap/global/exception/common/BusinessException.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorResponse.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/exception/jwt/JwtInvalidException.java
  src/main/java/piglin/swapswap/global/exception/jwt/NoJwtException.java
  src/main/java/piglin/swapswap/global/exception/jwt/UnsupportedGrantTypeException.java
  src/main/java/piglin/swapswap/global/exception/post/PostNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/user/EmailAlreadyExistException.java
  src/main/java/piglin/swapswap/global/exception/user/FailedLoginException.java
  src/main/java/piglin/swapswap/global/exception/user/PasswordMismatchedException.java
  src/main/java/piglin/swapswap/global/exception/user/UserAlreadyExistException.java
  src/main/java/piglin/swapswap/global/exception/user/UserNotFoundException.java
Labels: enhancement

#29 Feature: thymeleaf-layout 구성
  build.gradle
  src/main/resources/assets/favicon.ico
  src/main/resources/static/image/favicon/android-icon-144x144.png
  src/main/resources/static/image/favicon/android-icon-192x192.png
  src/main/resources/static/image/favicon/android-icon-36x36.png
  src/main/resources/static/image/favicon/android-icon-48x48.png
  src/main/resources/static/image/favicon/android-icon-72x72.png
  src/main/resources/static/image/favicon/android-icon-96x96.png
  src/main/resources/static/image/favicon/apple-icon-114x114.png
  src/main/resources/static/image/favicon/apple-icon-120x120.png
  src/main/resources/static/image/favicon/apple-icon-144x144.png
  src/main/resources/static/image/favicon/apple-icon-152x152.png
  src/main/resources/static/image/favicon/apple-icon-180x180.png
  src/main/resources/static/image/favicon/apple-icon-57x57.png
  src/main/resources/static/image/favicon/apple-icon-60x60.png
  src/main/resources/static/image/favicon/apple-icon-72x72.png
  src/main/resources/static/image/favicon/apple-icon-76x76.png
  src/main/resources/static/image/favicon/apple-icon-precomposed.png
  src/main/resources/static/image/favicon/apple-icon.png
  src/main/resources/static/image/favicon/browserconfig.xml
  src/main/resources/static/image/favicon/favicon-16x16.png
  src/main/resources/static/image/favicon/favicon-32x32.png
  src/main/resources/static/image/favicon/favicon-96x96.png
  src/main/resources/static/image/favicon/favicon.ico
  src/main/resources/static/image/favicon/manifest.json
  src/main/resources/static/image/favicon/ms-icon-144x144.png
  src/main/resources/static/image/favicon/ms-icon-150x150.png
  src/main/resources/static/image/favicon/ms-icon-310x310.png
  src/main/resources/static/image/favicon/ms-icon-70x70.png
  src/main/resources/static/image/logo/swapswaphomepagelogo.png
  src/main/resources/static/image/logo/swapswaplogo.png
  src/main/resources/static/style.css
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/common/layout/layout.html
  src/main/resources/templates/main.html
Labels: enhancement

#36 feat: 게시글 글쓰기 기능 추가
  build.gradle
  src/main/java/piglin/swapswap/domain/member/entity/Member.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/post/constant/PostConstant.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/S3Config.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/s3/S3ImageService.java
  src/main/java/piglin/swapswap/global/s3/S3ImageServiceImplV1.java
  src/main/resources/application.yml
  src/main/resources/static/style.css
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/post/postWrite.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#39 Feat: 쿠폰 생성 기능 추가
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/coupon/dto/request/CouponCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/coupon/mapper/CouponMapper.java
  src/main/java/piglin/swapswap/domain/coupon/repository/CouponRepository.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/coupon/validator/CouponValidator.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/coupon/CouponExpiredTimeException.java
  src/main/resources/static/style.css
  src/main/resources/templates/coupon/createCouponForm.html
Labels: enhancement

#41 refactor: createPost 매개변수 MemberId -> Member 변경
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: documentation

#47 Fix: Security 추가 후, 정적 리소스(css, js)가 적용되지 않은 버그 해결
  build.gradle
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/wallet/repository/WalletRepository.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/java/piglin/swapswap/global/jwt/JwtAuthenticationFilter.java
  src/main/java/piglin/swapswap/global/jwt/JwtCookieManager.java
  src/main/resources/static/css/style.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/favicon/android-icon-144x144.png
  src/main/resources/static/images/favicon/android-icon-192x192.png
  src/main/resources/static/images/favicon/android-icon-36x36.png
  src/main/resources/static/images/favicon/android-icon-48x48.png
  src/main/resources/static/images/favicon/android-icon-72x72.png
  src/main/resources/static/images/favicon/android-icon-96x96.png
  src/main/resources/static/images/favicon/apple-icon-114x114.png
  src/main/resources/static/images/favicon/apple-icon-120x120.png
  src/main/resources/static/images/favicon/apple-icon-144x144.png
  src/main/resources/static/images/favicon/apple-icon-152x152.png
  src/main/resources/static/images/favicon/apple-icon-180x180.png
  src/main/resources/static/images/favicon/apple-icon-57x57.png
  src/main/resources/static/images/favicon/apple-icon-60x60.png
  src/main/resources/static/images/favicon/apple-icon-72x72.png
  src/main/resources/static/images/favicon/apple-icon-76x76.png
  src/main/resources/static/images/favicon/apple-icon-precomposed.png
  src/main/resources/static/images/favicon/apple-icon.png
  src/main/resources/static/images/favicon/browserconfig.xml
  src/main/resources/static/images/favicon/favicon-16x16.png
  src/main/resources/static/images/favicon/favicon-32x32.png
  src/main/resources/static/images/favicon/favicon-96x96.png
  src/main/resources/static/images/favicon/favicon.ico
  src/main/resources/static/images/favicon/manifest.json
  src/main/resources/static/images/favicon/ms-icon-144x144.png
  src/main/resources/static/images/favicon/ms-icon-150x150.png
  src/main/resources/static/images/favicon/ms-icon-310x310.png
  src/main/resources/static/images/favicon/ms-icon-70x70.png
  src/main/resources/static/images/logo/swapswaphomepagelogo.png
  src/main/resources/static/images/logo/swapswaplogo.png
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: fix

#45 feat: 게시글 단 건 조회 기능 추가
  src/main/java/piglin/swapswap/domain/favorite/repository/FavoriteRepository.java
  src/main/java/piglin/swapswap/domain/favorite/service/FavoriteService.java
  src/main/java/piglin/swapswap/domain/favorite/service/FavoriteServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/post/post.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#50 bugfix: 로그인 안 한 사용자가 게시글을 작성할 수 있는 오류 수정
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
Labels: bug

#51 feat: 게시글 목록 조회 기능 추가
  build.gradle
  src/main/java/piglin/swapswap/domain/favorite/service/FavoriteServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/contorller/MainMvcController.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postList.html
Labels: enhancement

#55 test: favoriteServiceImplV1 테스트 코드 작성
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/test/java/piglin/swapswap/domain/favorite/service/FavoriteServiceImplV1UnitTest.java
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#59 feat: 게시글 수정 기능 추가
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/s3/S3ImageService.java
  src/main/java/piglin/swapswap/global/s3/S3ImageServiceImplV1.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postUpdateWrite.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#61 feat: 게시글 삭제 기능 추가
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/event/DeleteImageUrlEvent.java
  src/main/java/piglin/swapswap/domain/post/event/ImageEventListener.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/s3/S3ImageServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#64 feat: getPostList 반환 Page로 반환 하게 수정
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/post/postList.html
Labels: documentation, enhancement, fix

#66 feat: 게시글 검색 기능
  build.gradle
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/common/layout/layout.html
  src/main/resources/templates/main.html
  src/main/resources/templates/post/postList.html
Labels: enhancement

#75 refactor: 커서 기반 페이지네이션을 위한 N+1 방지 두방 쿼리 리팩토링
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/post/postList.html
Labels: bug, fix

#79 Feat: 선착순 쿠폰 발급에 따른 동시성 문제를 낙관적, 비관적 락으로 해결
  src/main/java/piglin/swapswap/domain/MemberCoupon/mapper/MemberCouponMapper.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/repository/MemberCouponRepository.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/service/MemberCouponService.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/service/MemberCouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/coupon/dto/request/CouponCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/coupon/entity/Coupon.java
  src/main/java/piglin/swapswap/domain/coupon/repository/CouponRepository.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/java/piglin/swapswap/global/annotation/Retry.java
  src/main/java/piglin/swapswap/global/aspect/RetryAspect.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/templates/common/layout/layout.html
  src/main/resources/templates/coupon/issueEventCoupon.html
  src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#83 Feat: 쿠폰 상세 페이지 및 기능 구현
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/coupon/dto/response/CouponGetResponseDto.java
  src/main/java/piglin/swapswap/domain/coupon/mapper/CouponMapper.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/resources/templates/coupon/couponDetail.html
Labels: enhancement

#85 Refactor: 이벤트 쿠폰 발급 페이지 재디자인 및 URL 변경
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/resources/static/css/style.css
  src/main/resources/static/images/eventcouponimage.png
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/coupon/issueEventCoupon.html
Labels: enhancement

#88 Fix: 쿠폰 Id, 이름 출력 오류 수정
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/resources/templates/coupon/couponDetail.html
  src/main/resources/templates/coupon/issueEventCoupon.html
Labels: fix

#89 Refactor: 쿠폰 CRUD 권한을 어드민으로 제한
  src/main/java/piglin/swapswap/domain/coupon/controller/AdminCouponController.java
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/member/constant/MemberRole.java
  src/main/java/piglin/swapswap/domain/member/entity/Member.java
  src/main/java/piglin/swapswap/domain/member/mapper/MemberMapper.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/java/piglin/swapswap/global/jwt/JwtUtil.java
  src/main/java/piglin/swapswap/global/security/UserDetailsImpl.java
  src/main/resources/templates/coupon/createCouponForm.html
  src/main/resources/templates/coupon/issueEventCoupon.html
  src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
Labels: good first issue

#87 Feat: 거래 요청 페이지 및 기능 구현
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/버그-발생.md
  .github/pull_request_template.md
  src/main/java/piglin/swapswap/domain/deal/constant/DealStatus.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostSimpleResponseDto.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/createDealForm.html
  src/main/resources/templates/deal/newcreateDealForm.html
  src/main/resources/templates/deal/updateDealForm.html
  src/main/resources/templates/post/post.html
Labels: enhancement

#95 Feature: 내 지갑 확인 페이지 및 기능 구현
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImpl.java
  src/main/resources/static/css/style.css
  src/main/resources/static/images/deposit.jpg
  src/main/resources/static/images/withdraw.jpg
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/member/mySwapMoney.html
Labels: enhancement, fix

#90 refactor: 게시글 단 건 조회 쿼리 개선
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/post/post.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: documentation, enhancement, fix

#96 refactor: 게시글 리스트 조회 매핑방식 fields -> constructor
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: fix

#98 feat: 내 찜 목록 확인 기능 추가
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/post/postFavoriteList.html
Labels: enhancement

#91 Feature: 내 쿠폰함 조회 페이지 및 기능 구현
  src/main/java/piglin/swapswap/domain/MemberCoupon/dto/response/MyCouponGetResponseDto.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/mapper/MemberCouponMapper.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/repository/MemberCouponRepository.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/service/MemberCouponService.java
  src/main/java/piglin/swapswap/domain/MemberCoupon/service/MemberCouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponService.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/member/myCouponList.html
  src/main/resources/templates/member/myPage.html
Labels: enhancement

#99 Feature: 지갑 입금 페이지 및 기능 구현
  src/main/java/piglin/swapswap/domain/member/repository/MemberQueryRepository.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java
  src/main/java/piglin/swapswap/domain/wallet/dto/request/DepositSwapMoneyRequestDto.java
  src/main/java/piglin/swapswap/domain/wallet/entity/Wallet.java
  src/main/java/piglin/swapswap/domain/wallet/service/WalletService.java
  src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/wallethistory/constant/HistoryType.java
  src/main/java/piglin/swapswap/domain/wallethistory/entity/WalletHistory.java
  src/main/java/piglin/swapswap/domain/wallethistory/mapper/WalletHistoryMapper.java
  src/main/java/piglin/swapswap/domain/wallethistory/repository/WalletHistoryRepository.java
  src/main/java/piglin/swapswap/domain/wallethistory/service/WalletHistoryService.java
  src/main/java/piglin/swapswap/domain/wallethistory/service/WalletHistoryServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/wallet/depositSwapMoney.html
Labels: enhancement

#104 fix: 게시글 아예 없을 때 예외 반환하는 오류 수정
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
Labels: bug

#106 fix: 찜 목록 게시글 아예 없을 때 예외 반환하는 오류 수정
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
Labels: bug

#107 fix: 찜 목록 게시글 아예 없을 때 예외 반환하는 오류 수정
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
Labels: bug

#102 Feat : 거래 요청 목록과 요청 받은 거래 목록 조회 기능 구현
  src/main/java/piglin/swapswap/domain/deal/constant/DealStatus.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealGetResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepository.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/deal/createDealForm.html
  src/main/resources/templates/deal/newcreateDealForm.html
  src/main/resources/templates/deal/requestDealList.html
  src/main/resources/templates/deal/responseDealList.html
Labels: enhancement

#108 Refactor: Service Layer의 입금/출금 메서드 공통화
  src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java
  src/main/java/piglin/swapswap/domain/wallet/service/WalletService.java
  src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/wallethistory/entity/WalletHistory.java
  src/main/java/piglin/swapswap/domain/wallethistory/mapper/WalletHistoryMapper.java
Labels: refactor

#110 Feat : 거래 상세 조회 기능 구현
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepository.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealCreateForm.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
  src/main/resources/templates/deal/updateDealForm.html
Labels: enhancement

#111 Feat : 거래 수정 기능 구현
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealUpdateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealUpdateForm.html
Labels: enhancement

#112 Feat : 거래 수락, 거래 인수 기능 구현
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealRequestDeal.html
Labels: enhancement

#113 Feat : 403 에러 관련해서 작성하였고 게시글 작성,수정이랑 쿠폰함 디자인 조금 바꿨습니다!
  src/main/java/piglin/swapswap/domain/member/contorller/MainMvcController.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/static/images/forbidden.PNG
  src/main/resources/templates/error/accessdenied.html
  src/main/resources/templates/member/mySwapMoney.html
  src/main/resources/templates/post/postUpdateWrite.html
  src/main/resources/templates/post/postWrite.html
Labels: enhancement, fix

#117 feat: 게시글 도시 Enum 추가
  src/main/java/piglin/swapswap/domain/post/constant/City.java
  src/main/java/piglin/swapswap/domain/post/constant/Province.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/request/PostCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/postWrite.html
Labels: enhancement

#123 HOTFIX: 패키지명 변경 Membercoupon -> membercoupon
  src/main/java/piglin/swapswap/domain/membercoupon/dto/response/MyCouponGetResponseDto.java
  src/main/java/piglin/swapswap/domain/membercoupon/entity/MemberCoupon.java
  src/main/java/piglin/swapswap/domain/membercoupon/mapper/MemberCouponMapper.java
  src/main/java/piglin/swapswap/domain/membercoupon/repository/MemberCouponRepository.java
  src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponService.java
  src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponServiceImplV1.java
Labels: bug, fix

#124 fix: Wallet 필드 변경에 따른 테스트 코드 수정
  src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
Labels: fix

#125 test: 테스트 코드 오류 수정
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: bug, fix

#126 fix: 게시글 등록 오류 수정
  src/main/resources/templates/common/fragments/nav.html
Labels: bug

#132 Swapswap Ver.1.0.1 배포
  src/main/resources/templates/common/fragments/nav.html
Labels: good first issue

#133 Swapswap Ver.1.0.2 배포
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: good first issue

#134 Swapswap Ver.1.0.3 배포
  Dockerfile
  src/main/resources/application.yml
Labels: good first issue

#135 Fix: 배포를 위한 kakao redirect url 변경
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/templates/member/login.html
  src/test/resources/application.yml
Labels: good first issue

#136 Swapswap Ver.1.0.4 배포
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/templates/member/login.html
  src/test/resources/application.yml
Labels: good first issue

#138 Fix: Thymleaf 템플릿 오류
  src/main/java/piglin/swapswap/domain/member/contorller/MainMvcController.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
Labels: fix

#140 Swapswap Ver.1.0.5 배포
  build.gradle
  src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
  src/main/java/piglin/swapswap/domain/chatroom/controller/StompController.java
  src/main/java/piglin/swapswap/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/interceptor/StompHandshakeInterceptor.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/chatroom_member/entity/ChatRoomMember.java
  src/main/java/piglin/swapswap/domain/chatroom_member/mapper/ChatRoomMemberMapper.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/message/constant/MessageType.java
  src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java
  src/main/java/piglin/swapswap/domain/message/dto/response/MessageResponseDto.java
  src/main/java/piglin/swapswap/domain/message/entity/Message.java
  src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageRepository.java
  src/main/java/piglin/swapswap/domain/message/service/MessageService.java
  src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java
  src/main/java/piglin/swapswap/global/config/WebSocketConfig.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/templates/chat/chatroom.html
  src/main/resources/templates/chat/chatroomList.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/post/post.html
Labels: enhancement

#141 Fix: Thymleaf memberId 오류 수정
  src/main/resources/templates/post/post.html
Labels: fix

#142 Swapswap Ver.1.0.6 배포
  src/main/resources/templates/post/post.html
Labels: enhancement

#144 Fix: 모든 채팅방이 보이는 버그 해결
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
Labels: fix

#145 Swapswap Ver.1.0.7 배포
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
Labels: fix

#147 feat: 게시글 거래 상태 컬럼 추가 및 출력
  src/main/java/piglin/swapswap/domain/deal/constant/DealStatus.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/member/login.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
  src/test/resources/application.yml
Labels: enhancement

#148 feat: 작성자가 아닐 시 수정, 업, 삭제 버튼 안뜨게 수정
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/resources/templates/post/post.html
Labels: refactor

#149 feat: 거래 내역 조회 기능 구현
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealHistoryResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealCreateForm.html
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
  src/main/resources/templates/member/myPage.html
Labels: enhancement

#150 doc: 이미지 최소 최대 문구 추가
  src/main/resources/application-prod.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/postUpdateWrite.html
  src/main/resources/templates/post/postWrite.html
Labels: documentation

#152 fix: Test 수정
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: fix

#151 Swapswap Ver.1.0.7 배포
  src/main/java/piglin/swapswap/domain/deal/constant/DealStatus.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealHistoryResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostGetResponseDto.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealCreateForm.html
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/myPage.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
  src/main/resources/templates/post/postUpdateWrite.html
  src/main/resources/templates/post/postWrite.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
  src/test/resources/application.yml
Labels: bug, documentation, enhancement

#157 fix: login.html call back 수정
  src/main/resources/templates/member/login.html
Labels: fix

#159 feat: 거래 상태에 따른 포스트에 거래상태 표시 기능 구현
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/post/post.html
Labels: enhancement

#160 Swapswap Ver.1.1.0 배포
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/entity/Post.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/post/post.html
Labels: enhancement

#162 Fix: 유저 닉네임 + 숫자 4개로 구성되도록 수정 및 프론트에서 중복된 닉네임 검사
  src/main/java/piglin/swapswap/domain/member/constant/AnimalAdjective.java
  src/main/java/piglin/swapswap/domain/member/constant/AnimalName.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/member/dto/MemberNicknameDto.java
  src/main/java/piglin/swapswap/domain/member/entity/Member.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/resources/templates/member/editProfile.html
Labels: enhancement, fix

#164 feat: 자신의 게시글 조회 시 채팅하기 버튼 안보이게 / 게시글 단건 조회 스타일 수정
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
Labels: enhancement

#165 fix: 게시글 등록 버튼 연타 시 계속 등록되던 상황 해결
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/post/postWrite.html
Labels: fix

#168 Feat: 스왑 페이와 거래 연동 기능 구현
  src/main/java/piglin/swapswap/domain/daelwallet/entity/DealWallet.java
  src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java
  src/main/java/piglin/swapswap/domain/daelwallet/repository/DealWalletRepository.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletService.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealUpdateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java
  src/main/resources/application-prod.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
Labels: enhancement

#170 Swapswap Ver.1.1.1 배포
  src/main/java/piglin/swapswap/SwapswapApplication.java
  src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
  src/main/java/piglin/swapswap/domain/chatroom/controller/StompController.java
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberRepository.java
  src/main/java/piglin/swapswap/domain/chatroom_member/service/ChatRoomMemberService.java
  src/main/java/piglin/swapswap/domain/chatroom_member/service/ChatRoomMemberServiceImpl.java
  src/main/java/piglin/swapswap/domain/daelwallet/entity/DealWallet.java
  src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java
  src/main/java/piglin/swapswap/domain/daelwallet/repository/DealWalletRepository.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletService.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealUpdateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/constant/AnimalAdjective.java
  src/main/java/piglin/swapswap/domain/member/constant/AnimalName.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/member/dto/MemberNicknameDto.java
  src/main/java/piglin/swapswap/domain/member/entity/Member.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java
  src/main/java/piglin/swapswap/domain/message/dto/response/MessageResponseDto.java
  src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/service/MessageService.java
  src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java
  src/main/java/piglin/swapswap/domain/post/mapper/PostMapper.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/domain/wallet/controller/WalletController.java
  src/main/resources/application-prod.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/chat/chatroom.html
  src/main/resources/templates/chat/chatroomList.html
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
  src/main/resources/templates/member/editProfile.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postWrite.html
Labels: enhancement, fix

#172 fix: 인수 시 withdrawMemberSwapMoneyAtComplete 메서드 실행 조건 변경
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
Labels: fix

#174 Fix: 채팅방 마지막 메시지와 시간이 업데이트되지 않는 버그 해결
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
Labels: fix

#173 HOTFIX: Swapswap Ver.1.1.1 배포
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
Labels: bug, fix

#175 Refactor: 거래 수락 파트 긴 코드 메서드화 및 쿼리 최적화
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
Labels: refactor

#176 style: 게시글 단 건 및 목록 조회 시 올린 날짜 표시 방법 수정
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement

#177 Swapswap Ver.1.1.2 배포
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement, refactor

#179 style: 게시글 단 건 조회 글 내용 개행 적용
  src/main/resources/static/css/style.css
Labels: fix

#180 fix: TimeZone 설정 제거
  src/main/java/piglin/swapswap/SwapswapApplication.java
Labels: bug, fix

#181 Swapswap Ver.1.1.3 배포
  src/main/java/piglin/swapswap/SwapswapApplication.java
  src/main/resources/static/css/style.css
Labels: bug, fix

#184 fix: 경상북도 안동시 오기입 / 충청남도 공주시 누락 수정
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/post/postUpdateWrite.html
  src/main/resources/templates/post/postWrite.html
Labels: fix

#189 style: 찜 버튼 잘 보이게 수정 / '게시일' 문구 삭제
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: fix

#192 Swapswap Ver.1.1.4 배포
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
  src/main/resources/templates/post/postUpdateWrite.html
  src/main/resources/templates/post/postWrite.html
Labels: fix

#194 fix: 게시글 단 건 조회 시 DealStatus 사진 뒤에 가려지던 오류 해결
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
Labels: fix

#195 HOTFIX: Swapswap Ver.1.1.4 배포
  src/main/resources/static/css/style.css
  src/main/resources/templates/post/post.html
Labels: fix

#201 HOTFIX: ChatRoomMember isDeleted 필드 추가로 인한 버그 해결
  src/main/java/piglin/swapswap/domain/chatroom_member/mapper/ChatRoomMemberMapper.java
Labels: fix

#207 feature: AOP 로깅을 위한 어노테이션 및 AOP 클래스 제작
  src/main/java/piglin/swapswap/global/annotation/SwapLog.java
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
Labels: enhancement

#212 feat: postListMore 메서드 isLast 필드로 더 이상 불러올 수 있는 지 확인으로 변경 / SweetAlert 적용
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostListDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/exception/post/NoMorePostListException.java
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: refactor

#209 feat: 거래 요청 기능 추가 및 deal, bill, billPost 생성
  src/main/java/piglin/swapswap/domain/bill/controller/BillController.java
  src/main/java/piglin/swapswap/domain/bill/dto/request/BillCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/bill/entity/Bill.java
  src/main/java/piglin/swapswap/domain/bill/mapper/BillMapper.java
  src/main/java/piglin/swapswap/domain/bill/repository/BillRepository.java
  src/main/java/piglin/swapswap/domain/bill/service/BillService.java
  src/main/java/piglin/swapswap/domain/bill/service/BillServiceImpl.java
  src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
  src/main/java/piglin/swapswap/domain/billpost/mapper/BillPostMapper.java
  src/main/java/piglin/swapswap/domain/billpost/repository/BillPostRepository.java
  src/main/java/piglin/swapswap/domain/billpost/service/BillPostService.java
  src/main/java/piglin/swapswap/domain/billpost/service/BillPostServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/post/AlreadyDealingPostException.java
  src/main/resources/templates/deal/dealCreateForm.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#213 Swapswap Ver.1.1.6 배포
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostListDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/post/dto/response/PostListResponseDto.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/annotation/SwapLog.java
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/exception/post/NoMorePostListException.java
  src/main/resources/templates/member/editProfile.html
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/member/unregister.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postListFragment.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement, fix, refactor

#208 Refactor: 엔티티간 연관관계를 가능한 가지지 않는 방향으로 리팩토링
  src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
  src/main/java/piglin/swapswap/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java
  src/main/java/piglin/swapswap/domain/message/dto/response/MessageResponseDto.java
  src/main/java/piglin/swapswap/domain/message/entity/Message.java
  src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageRepository.java
  src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java
  src/main/java/piglin/swapswap/global/security/UserDetailsImpl.java
  src/main/resources/templates/chat/chatroom.html
  src/main/resources/templates/chat/chatroomList.html
  src/main/resources/templates/post/post.html
Labels: refactor

#218 feat: 비 로그인 상태에서 찜 기능 작동 시 로그인 선택창 추가
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement

#216 feat: 게시글 띄어쓰기 생략 검색기능 추가 / 게시글 검색 후 전체보기 버튼 추가
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement

#221 fix: 게시글 지역 검색 후 More 메서드 실행 시 다른 지역 물품까지 불러오는 버그 수정
  src/main/resources/templates/post/postSearchList.html
Labels: bug

#222 Swapswap Ver.1.1.7 배포
  src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
  src/main/java/piglin/swapswap/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/repository/MemberRepository.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java
  src/main/java/piglin/swapswap/domain/message/dto/response/MessageResponseDto.java
  src/main/java/piglin/swapswap/domain/message/entity/Message.java
  src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageRepository.java
  src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/global/security/UserDetailsImpl.java
  src/main/resources/templates/chat/chatroom.html
  src/main/resources/templates/chat/chatroomList.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postSearchList.html
Labels: bug, enhancement, refactor

#224 feat: logback 설정 파일 추가
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
  src/main/resources/application.yml
  src/main/resources/log/appender/logback-local-console-appender.xml
  src/main/resources/log/appender/logback-prod-console-appender.xml
  src/main/resources/log/logback.xml
Labels: enhancement

#225 feat: 쿠폰 발급 및 memberCoupon 등록 logging
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponServiceImplV1.java
Labels: enhancement

#230 feat: post city 검색 바로 적용되게 수정 / Province 오타 수정
  src/main/java/piglin/swapswap/domain/post/constant/Province.java
  src/main/resources/templates/common/fragments/nav.html
Labels: enhancement

#227 feat: post create/update Logging
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
Labels: enhancement

#232 fix: 내 찜 목록에서 로그인이 필요하다는 버그 수정
  src/main/resources/templates/post/postFavoriteList.html
Labels: bug

#214 feat: 거래 상세 목록 조회 기능 추가
  src/main/java/piglin/swapswap/domain/billpost/entity/BillPost.java
  src/main/java/piglin/swapswap/domain/billpost/service/BillPostServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealGetReceiveDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealGetRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepository.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/deal/InvalidDealRequestException.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/layout/layout.html
  src/main/resources/templates/deal/dealCreateForm.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
Labels: enhancement

#233 test: 게시글 삭제 테스트 추가
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#228 Feat : 알림 기능 구현 및 UT 피드백 적용
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/notification/constant/NotificationType.java
  src/main/java/piglin/swapswap/domain/notification/controller/NotificationController.java
  src/main/java/piglin/swapswap/domain/notification/dto/NotificationCountDto.java
  src/main/java/piglin/swapswap/domain/notification/dto/NotificationResponseDto.java
  src/main/java/piglin/swapswap/domain/notification/entity/Notification.java
  src/main/java/piglin/swapswap/domain/notification/mapper/NotificationMapper.java
  src/main/java/piglin/swapswap/domain/notification/repository/EmitterRepository.java
  src/main/java/piglin/swapswap/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/notification/repository/NotificationRepository.java
  src/main/java/piglin/swapswap/domain/notification/service/NotificationService.java
  src/main/java/piglin/swapswap/domain/notification/service/NotificationServiceImpl.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/static/css/style.css
  src/main/resources/static/images/notification-empty.png
  src/main/resources/static/images/trash-closed.jpg
  src/main/resources/static/images/trash-open.jpg
  src/main/resources/static/js/nav.js
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/common/layout/layout.html
Labels: enhancement

#238 fix: 머지되면서 누락된 지역검색 추가
  src/main/resources/static/js/nav.js
Labels: fix

#241 feat: 거래 진행, 완료 게시글일 시 업 못하게 수정
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/ajax/AjaxRequestException.java
  src/main/java/piglin/swapswap/global/exception/comment/CommentNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/exception/post/PostNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/user/EmailAlreadyExistException.java
  src/main/java/piglin/swapswap/global/exception/user/FailedLoginException.java
  src/main/java/piglin/swapswap/global/exception/user/PasswordMismatchedException.java
  src/main/java/piglin/swapswap/global/exception/user/UserAlreadyExistException.java
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/post/post.html
Labels: enhancement

#243 refactor: security 재설정으로 인한 메소드 수정 및 테스트 코드 삭제
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: refactor
