Repository Team-Piglin/swapswap, pull requests merged in 2024-02, with the labels that each got.

#245 feat: Log HttpRequestLog / SwapLog 분리
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/global/annotation/HttpRequestLog.java
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
Labels: bug

#242 Swapswap Ver.1.1.8 배포
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/coupon/controller/CouponController.java
  src/main/java/piglin/swapswap/domain/coupon/service/CouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/contorller/MainMvcController.java
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/membercoupon/service/MemberCouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/notification/constant/NotificationType.java
  src/main/java/piglin/swapswap/domain/notification/controller/NotificationController.java
  src/main/java/piglin/swapswap/domain/notification/dto/NotificationCountDto.java
  src/main/java/piglin/swapswap/domain/notification/dto/NotificationResponseDto.java
  src/main/java/piglin/swapswap/domain/notification/entity/Notification.java
  src/main/java/piglin/swapswap/domain/notification/mapper/NotificationMapper.java
  src/main/java/piglin/swapswap/domain/notification/repository/EmitterRepository.java
  src/main/java/piglin/swapswap/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/notification/repository/NotificationRepository.java
  src/main/java/piglin/swapswap/domain/notification/service/NotificationService.java
  src/main/java/piglin/swapswap/domain/notification/service/NotificationServiceImpl.java
  src/main/java/piglin/swapswap/domain/post/constant/Province.java
  src/main/java/piglin/swapswap/domain/post/controller/PostController.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
  src/main/java/piglin/swapswap/global/annotation/HttpRequestLog.java
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/java/piglin/swapswap/global/exception/ajax/AjaxRequestException.java
  src/main/java/piglin/swapswap/global/exception/comment/CommentNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/java/piglin/swapswap/global/exception/common/GlobalExceptionHandler.java
  src/main/java/piglin/swapswap/global/exception/post/PostNotFoundException.java
  src/main/java/piglin/swapswap/global/exception/user/EmailAlreadyExistException.java
  src/main/java/piglin/swapswap/global/exception/user/FailedLoginException.java
  src/main/java/piglin/swapswap/global/exception/user/PasswordMismatchedException.java
  src/main/java/piglin/swapswap/global/exception/user/UserAlreadyExistException.java
  src/main/resources/application.yml
  src/main/resources/log/appender/logback-local-console-appender.xml
  src/main/resources/log/appender/logback-prod-console-appender.xml
  src/main/resources/log/logback.xml
  src/main/resources/static/css/style.css
  src/main/resources/static/images/notification-empty.png
  src/main/resources/static/images/trash-closed.jpg
  src/main/resources/static/images/trash-open.jpg
  src/main/resources/static/js/nav.js
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/common/fragments/nav.html
  src/main/resources/templates/common/layout/layout.html
  src/main/resources/templates/member/unregister.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postFavoriteList.html
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: bug, enhancement, fix, refactor

#247 Fix : 닉네임 수정이 되지 않던 버그 수정
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
Labels: bug, enhancement

#250 style : 알림창이 채팅방과 겹쳐보이는 현상 수정
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/resources/static/css/style.css
Labels: bug, fix

#248 HOTFIX: Swapswap Ver.1.1.8 배포
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/resources/static/css/style.css
Labels: bug, enhancement

#255 test: 게시글 업 테스트 코드 추가
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement

#256 HOTFIX: Swapswap Ver.1.1.9 배포
  src/main/java/piglin/swapswap/domain/post/service/PostService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/piglin/swapswap/domain/post/service/PostServiceImplV1UnitTest.java
Labels: enhancement, fix

#246 Feat: 거래 인수 기능 구현
  src/main/java/piglin/swapswap/domain/bill/billfacade/BillFacade.java
  src/main/java/piglin/swapswap/domain/bill/controller/BillController.java
  src/main/java/piglin/swapswap/domain/bill/entity/Bill.java
  src/main/java/piglin/swapswap/domain/bill/service/BillService.java
  src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletService.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/resources/templates/deal/dealRequestDeal.html
Labels: enhancement

#257 Feat: 거래내역 조회 기능 추가
  src/main/java/piglin/swapswap/domain/bill/billfacade/BillFacade.java
  src/main/java/piglin/swapswap/domain/bill/dto/request/BillAllowWithSwapPayRequestDto.java
  src/main/java/piglin/swapswap/domain/bill/mapper/BillMapper.java
  src/main/java/piglin/swapswap/domain/bill/repository/BillQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/bill/repository/BillRepository.java
  src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
  src/main/java/piglin/swapswap/domain/billcoupon/repository/BillCouponRepository.java
  src/main/java/piglin/swapswap/domain/billpost/repository/BillPostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/daelwallet/entity/DealWallet.java
  src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/dto/request/DealCreateRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealDetailResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealGetReceiveDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealGetRequestDto.java
  src/main/java/piglin/swapswap/domain/deal/dto/response/DealHistoryResponseDto.java
  src/main/java/piglin/swapswap/domain/deal/entity/Deal.java
  src/main/java/piglin/swapswap/domain/deal/mapper/DealMapper.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepository.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/deal/repository/DealRepository.java
  src/main/java/piglin/swapswap/domain/deal/service/DealService.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/global/exception/common/ErrorCode.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/deal/dealCreateForm.html
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/deal/dealRequestDeal.html
  src/main/resources/templates/deal/dealRequestDealListForm.html
  src/main/resources/templates/deal/dealResponseDealListForm.html
  src/main/resources/templates/deal/dealUpdateForm.html
  src/main/resources/templates/post/post.html
Labels: enhancement, fix

#259 Refactor: ChatRoom, Message의 저장소 변경 (MySQL -> MongoDB)
  build.gradle
  src/main/java/piglin/swapswap/domain/chatroom/controller/ChatRoomController.java
  src/main/java/piglin/swapswap/domain/chatroom/controller/StompController.java
  src/main/java/piglin/swapswap/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/piglin/swapswap/domain/chatroom/entity/ChatRoom.java
  src/main/java/piglin/swapswap/domain/chatroom/mapper/ChatRoomMapper.java
  src/main/java/piglin/swapswap/domain/chatroom/mongorepository/ChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/mongorepository/CustomChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/mongorepository/CustomChatRoomRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomService.java
  src/main/java/piglin/swapswap/domain/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/piglin/swapswap/domain/chatroom_member/entity/ChatRoomMember.java
  src/main/java/piglin/swapswap/domain/chatroom_member/mapper/ChatRoomMemberMapper.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberQueryRepository.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/chatroom_member/repository/ChatRoomMemberRepository.java
  src/main/java/piglin/swapswap/domain/chatroom_member/service/ChatRoomMemberService.java
  src/main/java/piglin/swapswap/domain/chatroom_member/service/ChatRoomMemberServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/KakaoServiceImpl.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/message/dto/request/MessageRequestDto.java
  src/main/java/piglin/swapswap/domain/message/entity/Message.java
  src/main/java/piglin/swapswap/domain/message/mapper/MessageMapper.java
  src/main/java/piglin/swapswap/domain/message/mongorepository/CustomMessageRepository.java
  src/main/java/piglin/swapswap/domain/message/mongorepository/CustomMessageRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/mongorepository/MessageRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepository.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/message/repository/MessageRepository.java
  src/main/java/piglin/swapswap/domain/message/service/MessageService.java
  src/main/java/piglin/swapswap/domain/message/service/MessageServiceImpl.java
  src/main/java/piglin/swapswap/global/config/JpaConfig.java
  src/main/java/piglin/swapswap/global/config/MongoConfig.java
  src/main/java/piglin/swapswap/global/scheduler/Scheduler.java
  src/main/resources/application-local.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/chat/chatroom.html
  src/main/resources/templates/chat/chatroomList.html
Labels: refactor

#260 feat: Bill / Deal / Wallet / Coupon 로깅 및 코드 컨벤션 맞게 조정 및 리팩토링
  src/main/java/piglin/swapswap/domain/bill/billfacade/BillFacade.java
  src/main/java/piglin/swapswap/domain/bill/controller/BillController.java
  src/main/java/piglin/swapswap/domain/bill/service/BillServiceImplV1.java
  src/main/java/piglin/swapswap/domain/billcoupon/controller/BillCouponController.java
  src/main/java/piglin/swapswap/domain/billcoupon/service/BillCouponService.java
  src/main/java/piglin/swapswap/domain/billcoupon/service/BillCouponServiceImplV1.java
  src/main/java/piglin/swapswap/domain/billpost/dto/BillPostResponseDto.java
  src/main/java/piglin/swapswap/domain/billpost/repository/BillPostQueryRepository.java
  src/main/java/piglin/swapswap/domain/billpost/repository/BillPostQueryRepositoryImpl.java
  src/main/java/piglin/swapswap/domain/billpost/service/BillPostService.java
  src/main/java/piglin/swapswap/domain/billpost/service/BillPostServiceImplV1.java
  src/main/java/piglin/swapswap/domain/daelwallet/mapper/DealWalletMapper.java
  src/main/java/piglin/swapswap/domain/daelwallet/service/DealWalletServiceImplV1.java
  src/main/java/piglin/swapswap/domain/deal/controller/DealController.java
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/domain/notification/service/NotificationServiceImpl.java
  src/main/java/piglin/swapswap/domain/wallet/service/WalletServiceImplV1.java
  src/main/java/piglin/swapswap/global/aspect/LogAspect.java
  src/main/resources/static/css/style.css
Labels: enhancement, fix

#262 feat: 게시글 검색 시 검색 결과 없으면 검색 결과 없다고 반환
  src/main/resources/static/css/style.css
  src/main/resources/templates/member/myPostList.html
  src/main/resources/templates/post/postFavoriteList.html
  src/main/resources/templates/post/postList.html
  src/main/resources/templates/post/postSearchList.html
Labels: enhancement

#264 Feat: 통합 테스트 환경을 구성하기 위한 Test Container 도입
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/piglin/swapswap/SwapswapApplicationTests.java
  src/test/java/piglin/swapswap/TCIntegrationTest.java
  src/test/java/piglin/swapswap/domain/coupon/service/CouponServiceTest.java
  src/test/resources/application.yml
  src/test/resources/docker_compose.yml
Labels: enhancement

#263 Feat: 게시글에서 닉네임 클릭 시 해당 멤버 프로필 및 게시글 조회 기능 구현
  src/main/java/piglin/swapswap/domain/member/contorller/MemberController.java
  src/main/java/piglin/swapswap/domain/member/dto/OtherMemberInfoDto.java
  src/main/java/piglin/swapswap/domain/member/mapper/MemberMapper.java
  src/main/java/piglin/swapswap/domain/member/service/MemberService.java
  src/main/java/piglin/swapswap/domain/member/service/MemberServiceImplV1.java
  src/main/java/piglin/swapswap/global/config/WebSecurityConfig.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/fragments/head.html
  src/main/resources/templates/member/editProfile.html
  src/main/resources/templates/member/otherMemberInfo.html
  src/main/resources/templates/post/post.html
Labels: enhancement

#265 feat: delete Scheduler 한시적 미사용 변경
  src/main/java/piglin/swapswap/global/scheduler/Scheduler.java
Labels: enhancement

#269 HOTFIX: Swapswap Ver.2.0.0 배포 CI
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: bug, fix

#270 HOTFIX: Swapswap Ver.2.0.0 배포
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: bug, fix

#271 fix: logback Include 수정, logback.xml -> logback-spring.xml 및 위치변경
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: bug, fix

#272 HOTFIX: Swapswap Ver.2.0.0 배포
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: bug, fix

#275 fix: Deal Notification Null 값들어가는 오류 해결
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
Labels: bug, fix

#276 HOTFIX: Swapswap Ver.2.0.0 배포
  src/main/java/piglin/swapswap/domain/deal/service/DealServiceImplV1.java
  src/main/resources/templates/deal/dealHistory.html
  src/main/resources/templates/post/post.html
Labels: bug, fix

#277 HOTFIX: Swapswap Ver.2.0.0 배포
  src/main/resources/application-prod.yml
Labels: fix

#278 feat: test 환경 logback 추가
  src/test/resources/logback-test.xml
Labels: enhancement

#279 fix: 게시글 검색 띄어쓰기 일치해도 검색 안되는 오류 수정
  src/main/java/piglin/swapswap/domain/post/repository/PostQueryRepository.java
  src/main/java/piglin/swapswap/domain/post/service/PostServiceImplV1.java
Labels: fix
